import { readFileSync, writeFileSync } from "node:fs"
import assert from "node:assert/strict"
function edit(file, before, after) {
  const text = readFileSync(file, "utf8")
  if (text.includes(after)) return
  assert.equal(text.split(before).length, 2, `Expected one anchor: ${file}: ${before.slice(0, 90)}`)
  writeFileSync(file, text.replace(before, after))
}
edit("scripts/job-workspace-test.mjs", '  assert.equal(nonRepo.branchDone, true)', '  assert.equal(nonRepo.branchDone, false, "a non-repository cannot claim a successful branch switch")\n  assert.equal(nonRepo.branchUnavailable, true)')
edit("scripts/job-workspace-test.mjs", '  const watched = path.join(directory, "watched.txt")', `  processResults.push(\n    { code: 0, stdout: "true", stderr: "" },\n    { code: 1, stdout: "", stderr: "switch failed" },\n    { code: 1, stdout: "", stderr: "create failed" },\n  )\n  const failedBranch = { branch: "cannot-switch" }\n  await runtime.ensureBranch(directory, failedBranch, client, "session")\n  assert.equal(failedBranch.branchDone, false, "failed switch/create must not admit work on the wrong branch")\n\n  const watched = path.join(directory, "watched.txt")`)
edit("src/source/opencode2/native-runtime.js", 'request = { sessionID: scope.sessionID, name, ...(text ? { text } : {}), delivery: "queue" }', 'request = { sessionID: scope.sessionID, name, text: text || "", delivery: "queue" }')
edit("scripts/opencode2-loop-canary.mjs", 'return job?.paused === false && job?.lastRunAt === 0', 'return job?.paused === false && (job?.lastRunAt === 0 || job?.runNowRequestedAt > 0)')
edit("scripts/opencode2-loop-canary.mjs", '    console.log(JSON.stringify({\n      ok: true,', `    if (process.env.OPENCODE2_NATIVE_REQUIRED === "1") {\n      const nativeLog = await readFile(path.join(workspace, ".opencode/opencode-loop/loop.log"), "utf8")\n      assert.match(nativeLog, /v2-native-ready/, "the real host must load the native implementation")\n      assert.match(nativeLog, /v2-native-admitted/, "the native implementation must own the admissions")\n      await writeFile(path.join(workspace, "native-preflight.cjs"), 'require("node:fs").appendFileSync("native-preflight.txt", "P")')\n      await writeFile(path.join(workspace, "native-verify.cjs"), 'require("node:fs").appendFileSync("native-verify.txt", "V")')\n      await sendControl("loop", '0s native verified task --max-runs 1 --name verified --preflight "node native-preflight.cjs" --verify "node native-verify.cjs"')\n      await waitFor(async () => {\n        const job = await jobNamed("verified")\n        return job?.runCount === 1 && !job.v2Run && job.lastVerifyCode === 0\n      }, "native preflight and post-turn verification", diagnostics, 30_000)\n      assert.equal(await readFile(path.join(workspace, "native-preflight.txt"), "utf8"), "P")\n      assert.equal(await readFile(path.join(workspace, "native-verify.txt"), "utf8"), "V")\n      await sendControl("loop-clear")\n      await sendControl("loop-shell", '0s node native-preflight.cjs --max-runs 1 --name native-shell')\n      await waitFor(async () => {\n        const job = await jobNamed("native-shell")\n        return job?.runCount === 1 && !job.v2Run\n      }, "native shell terminal correlation", diagnostics, 20_000)\n      assert.equal(await readFile(path.join(workspace, "native-preflight.txt"), "utf8"), "PP")\n      await sendControl("loop-clear")\n    }\n\n    console.log(JSON.stringify({\n      ok: true,`)
console.log("Native review regressions applied")
